In [1]:
import numpy as np

In [6]:
list1 = [1,2,3,4,5]
list2 = [3,64,12,75,2]

In [7]:
array1 = np.array([list1,list2])

In [8]:
array1

array([[ 1,  2,  3,  4,  5],
       [ 3, 64, 12, 75,  2]])

In [9]:
array1.shape

(2, 5)

In [11]:
array1.size

10

In [14]:
array1.dtype

dtype('int32')

In [16]:
array1.ndim

2

In [18]:
array1.itemsize

4

In [ ]:
np.zeros()

In [19]:
np.empty((2,3),dtype="float32")

array([[  6.33844643e+29,   9.46984954e+21,  -1.56703470e-22],
       [  8.78614137e-43,   0.00000000e+00,  -0.00000000e+00]], dtype=float32)

In [20]:
array2 = np.array(list1)

In [21]:
array2

array([1, 2, 3, 4, 5])

In [22]:
array2[2]

3

In [23]:
array2[1:3]

array([2, 3])

In [24]:
array1

array([[ 1,  2,  3,  4,  5],
       [ 3, 64, 12, 75,  2]])

In [28]:
b = np.linspace(2,20,9).reshape(3,3)

In [29]:
b

array([[  2.  ,   4.25,   6.5 ],
       [  8.75,  11.  ,  13.25],
       [ 15.5 ,  17.75,  20.  ]])

In [31]:
b[:2,1:]

array([[  4.25,   6.5 ],
       [ 11.  ,  13.25]])

In [32]:
b

array([[  2.  ,   4.25,   6.5 ],
       [  8.75,  11.  ,  13.25],
       [ 15.5 ,  17.75,  20.  ]])