In [1]:
import numpy as np


In [2]:
np.random.randn(10)

array([-0.00866082,  1.28670584, -0.5463567 , -0.3082069 , -0.33125896,
        0.65623074,  0.26577312,  0.5472789 , -0.61106235,  2.35463873])

In [7]:
np.random.randint(10,size=(5,4))

array([[2, 5, 9, 3],
       [5, 7, 9, 5],
       [6, 8, 8, 4],
       [2, 0, 9, 8],
       [3, 6, 5, 8]])

In [9]:
a = np.random.randint(10,size=(4,5))
a

array([[3, 4, 7, 6, 3],
       [1, 0, 6, 1, 6],
       [2, 7, 7, 9, 9],
       [5, 7, 2, 6, 8]])

In [10]:
b = np.random.randint(10,size=(4,5))
b

array([[6, 9, 6, 1, 5],
       [0, 0, 5, 2, 3],
       [8, 5, 2, 9, 4],
       [5, 1, 6, 2, 8]])

In [12]:
c = a+b
c

array([[ 9, 13, 13,  7,  8],
       [ 1,  0, 11,  3,  9],
       [10, 12,  9, 18, 13],
       [10,  8,  8,  8, 16]])

In [13]:
a/b

D:\tools\Anaconda3\envs\py362\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.
D:\tools\Anaconda3\envs\py362\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([[ 0.5       ,  0.44444444,  1.16666667,  6.        ,  0.6       ],
       [        inf,         nan,  1.2       ,  0.5       ,  2.        ],
       [ 0.25      ,  1.4       ,  3.5       ,  1.        ,  2.25      ],
       [ 1.        ,  7.        ,  0.33333333,  3.        ,  1.        ]])

In [14]:
a+2

array([[ 5,  6,  9,  8,  5],
       [ 3,  2,  8,  3,  8],
       [ 4,  9,  9, 11, 11],
       [ 7,  9,  4,  8, 10]])

In [15]:
a+100

array([[103, 104, 107, 106, 103],
       [101, 100, 106, 101, 106],
       [102, 107, 107, 109, 109],
       [105, 107, 102, 106, 108]])

In [16]:
a*b

array([[18, 36, 42,  6, 15],
       [ 0,  0, 30,  2, 18],
       [16, 35, 14, 81, 36],
       [25,  7, 12, 12, 64]])

In [17]:
a

array([[3, 4, 7, 6, 3],
       [1, 0, 6, 1, 6],
       [2, 7, 7, 9, 9],
       [5, 7, 2, 6, 8]])

In [19]:
np.unique(a)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
sum(a)

array([11, 18, 22, 22, 26])

In [29]:
np.sum(a,axis=1)

array([23, 14, 34, 28])

In [30]:
np.sum(a,axis=0)

array([11, 18, 22, 22, 26])

In [31]:
np.max(a)

9

In [32]:
np.min(a)

0

In [33]:
np.min(a,axis=0)

array([1, 0, 2, 1, 3])