## 使用pickle 序列化numpy array

In [1]:
import pickle
import numpy as np

In [2]:
x = np.arange(10)

In [3]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
f = open("x01.pkl","wb")

In [8]:
pickle.dump(x,f)

In [10]:
f = open("x01.pkl","rb")

In [11]:
pickle.load(f)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## np.save(file, arr, allow_pickle=True, fix_imports=True)

In [13]:
np.save("onr_array01",x)

In [16]:
np.load("onr_array01.npy")

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
y = np.arange(20)
y

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [18]:
np.save("one_array02.npy",y)

In [19]:
np.load("one_array02.npy")

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [25]:
np.savez("two_array01.npz",x=x,y=y)

In [26]:
c = np.load("two_array01.npz")

In [27]:
c["x"]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
c["y"]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])