In [1]:
import numpy as np
import pandas as pd

In [2]:
s1 = pd.Series([1,2,3,4,5,6])

In [3]:
s1

0    1
1    2
2    3
3    4
4    5
5    6
dtype: int64

In [5]:
s1.values

array([1, 2, 3, 4, 5, 6], dtype=int64)

In [6]:
s1.index

RangeIndex(start=0, stop=6, step=1)

## np

In [11]:
s2 = pd.Series(np.arange(10))

In [12]:
s2

0    0
1    1
2    2
3    3
4    4
5    5
6    6
7    7
8    8
9    9
dtype: int32

In [39]:
s3 = pd.Series({"1":3,"2":2,"3":3})

In [40]:
s3

1    3
2    2
3    3
dtype: int64

In [15]:
s3.values

array([1, 2, 3], dtype=int64)

In [16]:
s3.index

Index(['1', '2', '3'], dtype='object')

## 指定index  
#### pd.Series(data=None, index=None, dtype=None, name=None,               copy=False, fastpath=False)

In [21]:
s4 = pd.Series(data=[1,2,3,4],index=["A","B","C","D"],dtype="float32")


In [22]:
s4

A    1.0
B    2.0
C    3.0
D    4.0
dtype: float32

In [23]:
s4.index

Index(['A', 'B', 'C', 'D'], dtype='object')

In [24]:
s4.values

array([ 1.,  2.,  3.,  4.], dtype=float32)

In [25]:
s4["A"]

1.0

In [26]:
s4[s4>2]

C    3.0
D    4.0
dtype: float32

In [28]:
s4.to_dict()

{'A': 1.0, 'B': 2.0, 'C': 3.0, 'D': 4.0}

In [30]:
s5 = pd.Series(s4.to_dict())

In [31]:
s5

A    1.0
B    2.0
C    3.0
D    4.0
dtype: float64

In [32]:
index_1 = ['A', 'B', 'C', 'D',"E"]

In [35]:
s6 = pd.Series(s5,index = index_1)

In [36]:
s6

A    1.0
B    2.0
C    3.0
D    4.0
E    NaN
dtype: float64

In [38]:
s6.values

array([  1.,   2.,   3.,   4.,  nan])